"""Конфигурация приложения."""

from .settings import (
    DB_PATH,
    DEFAULT_SERVICE_CATEGORIES,
    DUTY_PHARMACY_CATEGORY,
    MAX_CATEGORY_NAME_LENGTH,
    MAX_IMPORT_REMINDERS,
    MAX_REMINDER_TEXT_LENGTH,
    MAX_SERVICE_CONTACT_LENGTH,
    MAX_SERVICE_NOTES_LENGTH,
    MAX_SERVICE_TITLE_LENGTH,
)

__all__ = [
    "DB_PATH",
    "DEFAULT_SERVICE_CATEGORIES",
    "DUTY_PHARMACY_CATEGORY",
    "MAX_CATEGORY_NAME_LENGTH",
    "MAX_IMPORT_REMINDERS",
    "MAX_REMINDER_TEXT_LENGTH",
    "MAX_SERVICE_CONTACT_LENGTH",
    "MAX_SERVICE_NOTES_LENGTH",
    "MAX_SERVICE_TITLE_LENGTH",
]
